name: Automate Issues to Project
on:
  issues:
    types:
      - opened
      - reopened
      - closed
      - assigned
    permissions:
      contents: read
      issues: write
      project: write

jobs:
  issue_opened_and_reopened:
    name: issue_opened_and_reopened
    runs-on: ubuntu-24.04-arm
    if: github.repository == 'gnu-unbOS/issue-automation' && github.event_name == 'issues' && github.event.action == 'opened' || github.event.action == 'reopened'
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 'Move issue to "Triage"'
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        with:
          gh_token: ${{ steps.generate_token.outputs.token }}
          organization: gnu-unbOS
          project_id: 1
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: "Triage"
  issue_closed:
    name: issue_closed
    runs-on: ubuntu-24.04-arm
    if: github.repository == 'gnu-unbOS/issue-automation' &&  github.event_name == 'issues' && github.event.action == 'closed'
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 'Moved issue to "Done"'
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        with:
          gh_token: ${{ steps.generate_token.outputs.token }}
          organization: gnu-unbOS
          project_id: 1
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: "Done"
  issue_assigned:
    name: issue_assigned
    runs-on: ubuntu-24.04-arm
    if: github.repository == 'gnu-unbOS/issue-automation' &&  github.event_name == 'issues' && github.event.action == 'assigned'
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 'Move issue to "In Progress"'
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        with:
          gh_token: ${{ steps.generate_token.outputs.token }}
          organization: gnu-unbOS
          project_id: 1
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: "In Progress"
